name: Test and Build

on: [ pull_request, push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Test with Maven
        run: ./mvnw clean test
      - name: Pack with Maven
        run: ./mvnw clean package -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          path: ./target/*-runner.jar